export const SET_USER = "SET_USER";
export const INCREASE_SCANS_COUNT = "INCREASE_SCANS_COUNT";
export const INCREASE_CONFIRMED_APPLICATIONS =
  "INCREASE_CONFIRMED_APPLICATIONS";
export const INCREASE_APPROVED_APPLICATIONS = "INCREASE_APPROVED_APPLICATIONS";
export const INCREASE_REVIEWED_APPLICATIONS = "INCREASE_REVIEWED_APPLICATIONS";
export const ADD_APPLICATION = "ADD_APPLICATION";
export const SET_APPLICATION_IS_PROCESSED = "SET_APPLICATION_IS_PROCESSED";
export const SET_APPLICATION_IS_VIEWED = "SET_APPLICATION_IS_VIEWED";
export const SET_IS_AUTH = "SET_IS_AUTH";
